### ISSUE TITLE
Missing default chevron-down on selectedField

### ISSUE THREAD

**Issue by kure-** [Symphony9/pickathing#1]
the content of :before on .Pickathing-selectedField is empty. Should either contain down-arrow via some font or just simple arrow by picture.

Free-cool-in would be to setup the arrow as svg in pickathing options

**Comment by VojtechKlos** [comment]
Hello @kure-  and thank you for your comment.

I will be very happy to accept your mentions as a pull request. As of right no only making features that I think I will use on current or future projects. So a pull request is welcome.

Thanks ;-)
