### ISSUE TITLE
preselecte if a empty are present in multiple selects

### ISSUE THREAD

**Issue by mckaygerhard** [Symphony9/pickathing#3]
if a empty element are present pickathing preselect this as default, event are not defined in tag field, lest ilustrate : 

```
<td>Entidad Destino:</td><td><select name="cod_entidad[]"  id="cod_entidad"  multiple>
<option value="" ></option>
<option value="000">(0) ALM Almacen (NA)</option>
<option value="034">(34) RCS Los Ruices ()</option>
</select>
<script src="http://127.0.0.1/~systemas/appweb/scripts/pickathing.js">
</script>
<script>var selectcod_entidad = new Pickathing('cod_entidad', true);</script>
```

As can see, firts of the list its a "" record, then when browser render show preselected : 

![preselected-empty](https://cloud.githubusercontent.com/assets/1571724/23303740/309faa90-fa6c-11e6-9f49-5cd1be0c7a22.png)

## ANY IDEA HOW PICKATHING CAN AVOID THIS BEHAVIOR due i need send this firts empty element  to the select tag in some cases

OF COURSE IF I DO NOT SEND THIS EMPTY ELEMENT ARE SOLVED; BUT SOME CASES I AUTOBUILD THE SELECT TAG (including the script pickathing tag) FROM THE FRAMEWORK DIRECTLY WITH A SIMPLE QUERY

thanks in advance, great work!

**Comment by mckaygerhard** [comment]
note generated in time "selected" in the select tag, i canot determine if framework are doing this or pickathing, wheantime i research some more..

**Comment by mckaygerhard** [comment]
SOLVED! was the codeigniter form_helper

in form helper was a line : 

$sel = (in_array($key, $selected) ) ? ' selected="selected"' : '';

if i presend a variable reserved to "some value previous" from request:

'Entidad Destino:', form_dropdown('cod_entidad[]', $arrayentidad,$cod_entidad, ' multiple') ;

when "$cod_entidad" are empty the form helper make it as preselected (of course are in third parameter) that's incorrect, so modify the dropdown to only preselect valid values..

of course with normal "select" tags this are ambigous, that default selected "" are show to users as a empty input filed, forcing to user to choose

**Comment by VojtechKlos** [comment]
OK I was just about to write that it seems to be problem somewhere on your side because I couldnt reproduce it. Glad you solved it ;-)
