### ISSUE TITLE
Uncaught SyntaxError: <unknown message reserved_word> 

### ISSUE THREAD

**Issue by mckaygerhard** [Symphony9/pickathing#6]
Since some changes where made to pickathing, now gives me erros in many clients.. 

```
Uncaught SyntaxError: <unknown message reserved_word> 
```

due that now i have:

```
Uncaught ReferenceError: Pickathing is not defined index.html:84
(anonymous function)
```

**Comment by VojtechKlos** [comment]
Hey. Can you please specify the clients that it does not work in? I cannot seem to reproduce the error, thanks.

**Comment by mckaygerhard** [comment]
grrrr, seems stupid cache problems on "chrome" for stupid os guindows..  working on linux..

i'll test at my home qnd in few hours i'll close.. if all are ok i'll integrate it again in my codeigniterpower all the comboboxes and select's will be as pickathing reders...

**Comment by mckaygerhard** [comment]
grrrr, seems stupid cache problems on "chrome" for stupid os guindows..  working on linux..

i'll test at my home qnd in few hours i'll close.. if all are ok i'll integrate it again in my codeigniterpower all the comboboxes and select's will be as pickathing reders...

**Comment by mckaygerhard** [comment]
in the weekend, internet connection was gone! so i cannot test yet! give me some hours and then i'll close or not this issue

**Comment by VojtechKlos** [comment]
Do you have any news on this issue?

**Comment by mckaygerhard** [comment]
close it! it working, google chrome cache its a pain!
